services:
  frontend:
    build:
      context: .
      dockerfile: ../DOCKERFILES/webpage  # Correct path to DOCKERFILES/webpage
    ports:
      - "5000:5000"
    networks:
      - thetazero-net
    volumes:
      - ./frontend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  whisper:
    build:
      context: .
      dockerfile: ../DOCKERFILES/whisper  # Correct path to DOCKERFILES/whisper
    ports:
      - "8000:8000"
    networks:
      - thetazero-net
    environment:
      - FLASK_APP=app.py
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

networks:
  thetazero-net:
    driver: bridge
